-
  image: Visual Studio 2017

  build_script:
    - cmd: .\dogfood.cmd

-
  environment:
    MYGET_API_KEY:
      secure: CcB8bliXM24AjTLTpLuw+fmo3he7VCnZzUWleNxN2bvbYLvrRMl9EellX5jMLqTG

  branches:
    only:
    - master

  image: Visual Studio 2017

  build_script:
    - cmd: .\dogfood.cmd

  on_success:
    - cmd: .\push.cmd "MyGet - Casper (AppVeyor)"
