#! /bin/sh

myDir="`dirname \"$0\"`"
localNugetConfig=$myDir/local-nuget.config

echo Installing old Casper...
oldPackageDir=$myDir/.casper/old
mkdir -p $oldPackageDir
$myDir/nuget install Casper.Console -Version 0.1.0-ci0146 -OutputDirectory $oldPackageDir -pre -Verbosity quiet -Source "MyGet" -ConfigFile $localNugetConfig -ExcludeVersion || exit $?
