#! /bin/sh

myDir="`dirname \"$0\"`"
configuration=${1:-Release}

echo Building with xbuild...
xbuild /p:Configuration=$configuration /verbosity:quiet /nologo || exit $?
$myDir/pack $configuration || exit $?
