#! /bin/sh

myDir="`dirname \"$0\"`"
configuration=${1:-Release}

echo Restoring dependencies...
$myDir/nuget restore || exit $?

echo Determining version...
$myDir/gitversion || exit $?

echo Building with msbuild...
msbuild /p:Configuration=$configuration /verbosity:quiet /nologo || exit $?
$myDir/pack $configuration || exit $?
