#! /bin/sh

myDir="`dirname \"$0\"`"
configuration=${1:-Release}

echo Restoring dependencies...
$myDir/nuget restore || exit $?

echo Determining version...
mono packages/GitVersion.CommandLine.3.6.5/tools/GitVersion.exe /updateAssemblyInfo AssemblyInfo.Version.cs /ensureAssemblyInfo || exit $?

echo Building with msbuild...
msbuild /p:Configuration=$configuration /verbosity:quiet /nologo || exit $?
$myDir/pack $configuration || exit $?
