#! /bin/sh

task=${1:-Build}

myDir="`dirname \"$0\"`"
casperPath=`find $myDir/.msbuild -name "Casper.Console.*" -type d`
echo "Running casper..."
mono --debug $casperPath/tools/casper.exe build.casper $task
