#! /bin/sh

myDir="`dirname \"$0\"`"
configuration=${1:-Release}

rm -r $myDir/out
mkdir -p $myDir/out/packages
$myDir/nuget pack $myDir/Console/Console.nuspec -OutputDirectory $myDir/out/packages -Properties "BINPATH=bin/$configuration/" || exit $?
