#! /bin/sh

myDir="`dirname \"$0\"`"
configuration=${1:-Release}

version=$(./gitversion) || exit $?

rm -r $myDir/out
mkdir -p $myDir/out/packages
echo Packing version $version
$myDir/nuget pack $myDir/Console/Console.nuspec -OutputDirectory $myDir/out/packages -Properties "BINPATH=bin/$configuration/" -NoPackageAnalysis -Version $version || exit $?
