#! /bin/sh

myDir="`dirname \"$0\"`"
feed="$1"

echo Pushing package to "$feed"...
$myDir/nuget push $myDir/out/packages/$(ls $myDir/out/packages/) $MYGET_API_KEY -ConfigFile local-nuget.config -Source "$feed" -NonInteractive || exit $?
